### ISSUE TITLE
LoadError while "using C3D"

### ISSUE THREAD

**Issue by AliaaRassem** [halleysfifthinc/C3D.jl#4]
After I cloned the package by:
Pkg.clone("https://github.com/halleysfifthinc/C3D.jl.git"),

and tried to:
using C3D

it requires "VaxData" Package, so I cloned it by:
Pkg.clone("https://github.com/halleysfifthinc/VaxData.jl.git"),

then I tried again to:
using C3D

This error appears:
----------------------------------------------------------
ERROR: LoadError: LoadError: UndefVarError: @debug not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /home/user/.julia/v0.6/C3D/src/parameters.jl, in expression starting on line 67
while loading /home/user/.julia/v0.6/C3D/src/C3D.jl, in expression starting on line 11
ERROR: Failed to precompile C3D to /home/user/.julia/lib/v0.6/C3D.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405
----------------------------------------------------------

I use julia 0.6.2 on ubuntu 14

Thanks,

**Comment by halleysfifthinc** [comment]
Both the C3D and VaxData packages only work on v0.7 since the majority of the recent work I've done on these is so close to the release of v0.7; it made more sense to just drop the support of v0.6.x.

If, at the moment, you are just evaluating this package, I would recommend installing the latest beta of v0.7. The main issue I have found at this point with using v0.7 is a lack of v0.7 support in other packages. So depending on what other packages you need, you may or may not be able to just upgrade to v0.7.
